fix script

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,13 @@
 
 npm run format
 npm run lint:fix
+
+
+
+# exit if there are un-staged changes
+if ! git diff --exit-code; then
+  echo "There are un-staged changes. Aborting."
+  exit 1
+fi
 echo "All checks passed!"
 
